let cloudset = {
    imgset_01:[
        '',
        '',
        '',
        ''
    ],
    imgset_02:[
        './weather_icons/others/whiteCloud.svg',
        '',
        './weather_icons/others/whiteCloud.svg',
        ''
    ],
    imgset_03:[
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg'
    ],
    imgset_04:[
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg'
    ],
    imgset_09:[
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg'
    ],
    imgset_10:[
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg'
    ],
    imgset_11:[
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg',
        './weather_icons/others/darkcloud.svg'
    ],
    imgset_13:[
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg',
        './weather_icons/others/whiteCloud.svg'
    ],
    imgset_50:[
        '',
        '',
        './weather_icons/others/whiteCloud.svg',
        ''
    ]
}

export {cloudset}